symfony/check_tasks/home10/src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $voteCount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="articles")
     */
    private $tags;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getVoteCount(): ?int
    {
        return $this->voteCount;
    }

    public function setVoteCount(?int $voteCount): self
    {
        $this->voteCount = $voteCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return 'images/' . $this->getImageFilename();
    }

    public function getAvatarPath(): ?string
    {
        return 'https://robohash.org/' . $this->getAuthor() . '.png?set=set3';
    }

    public function voteUp()
    {
        $this->voteCount++;
        return $this;
    }

    public function voteDown()
    {
        $this->voteCount--;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }
}

symfony/check_tasks/home10/src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    private static $maxLastComments = 3;

    /**
     * @Route("/", name="app_articles_index")
     * @param ArticleRepository $articleRepository
     * @param CommentRepository $commentRepository
     * @return Response
     */
    public function homepage(ArticleRepository $articleRepository, CommentRepository $commentRepository)
    {
        return $this->render('articles/index.html.twig', [
            'articles' => $articleRepository->findLatestPublished(),
            'lastComments' => $commentRepository->getLastComments(self::$maxLastComments),
        ]);
    }

    /**
     * @Route("/articles/{slug}", name="app_articles_show")
     * @param Article $article
     * @return Response
     */
    public function show(Article $article)
    {
        return $this->render('articles/show.html.twig', ['article' => $article]);
    }

    /**
     * @Route("/articles/{slug}/vote/up", name="app_articles_vote_up", methods={"POST"})
     * @param Article $article
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function voteUp(Article $article, EntityManagerInterface $em)
    {
        $article->voteUp();
        $em->flush();
        return $this->json(['votes' => $article->getVoteCount()]);
    }

    /**
     * @Route("/articles/{slug}/vote/down", name="app_articles_vote_down", methods={"POST"})
     * @param Article $article
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function voteDown(Article $article, EntityManagerInterface $em)
    {
        $article->voteDown();
        $em->flush();
        return $this->json(['votes' => $article->getVoteCount()]);
    }

}

symfony/check_tasks/home10/templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Главная{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">

            <div class="col-sm-12">
                <div class="row">
                    <div class="col-md-12 col-xl-8">

                        {% for article in articles %}

                            <div class="article-container mb-2">
                                <div class="row no-gutters border flex-md-row p-3 mb-4 shadow-sm">
                                    <div class="col-auto d-block">
                                        {% if article.imageFilename  %}
                                            <img class="article-img" src="{{ asset(article.imagePath) }}">
                                        {% else %}
                                            <img class="article-img" src="http://placehold.it/240x150">
                                        {% endif %}
                                    </div>
                                    <a class="col px-4 d-flex flex-column article-item" href="{{ path('app_articles_show', {slug: article.slug}) }}">
                                        <h5 class="mb-2">{{ article.title }}</h5>
                                        <div class="d-flex mb-2">
                                            {% if article.author %}
                                                <div class="text-muted align-self-center">
                                                    <img class="article-author-img rounded-circle" src="{{ article.avatarPath }}">
                                                    {{ article.author }}
                                                </div>
                                            {% endif %}
                                            <div class="text-muted align-self-center ml-3"><i class="fas fa-clock size-is-"></i>
                                                {{ article.publishedAt ? article.publishedAt|ago : 'Не опубликована' }}
                                            </div>
                                        </div>
                                        <div class="mb-2 d-flex">
                                            <span class="badge badge-primary mr-2"><i class="fas fa-comment"></i> {{ article.nonDeletedComments|length }}</span>
                                            {% if article.tags|length %}
                                                {% include 'partial/article_tags.html.twig' with { tags: article.tags } %}
                                            {% endif %}
                                        </div>
                                        <div class="mb-2 text-muted">
                                            <p>{{ article.description }}</p>
                                        </div>
                                    </a>
                                </div>
                            </div>

                        {% endfor %}

                     </div>

                    <div class="col-md-12 col-xl-4">
                        <div class="text-center bg-primary text-white py-1 border border-bottom-0">
                            <h4 class="mb-0">Последние комменты</h4>
                        </div>
                        <div class="quotes-container bg-white shadow-sm border border-top-0 pb-2 pt-2 px-5">

                            {% for comment in lastComments %}
                                <div class="border-bottom mb-3">
                                    <div class="h4 text-left">{{ comment.article.title }} </div>
                                    <p><i class="far fa-comment text-secondary"></i> {{ comment.content|cached_markdown }}
                                        <br> — <a href="/">{{ comment.authorName }}</a></p>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

symfony/check_tasks/home10/templates/articles/show.html.twig
{% extends 'base_content.html.twig' %}

{% block title %}{{ article.title ~ ' - ' ~ 'учебный блог на Symfony' }}{% endblock %}
{% block keywords %}{{ article.keywords ? article.keywords }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/detail.css') }}">
{% endblock %}
{% block content_row_class %}article-detail{% endblock %}
{% block content_col_class %}border flex-md-row mb-4 shadow-sm bg-white p-4{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/vote.js') }}"></script>
{% endblock %}

{% block content %}

    <div class="col-sm-12 p-2">
        <div class="media d-flex align-content-center">
            {% if (article.imageFilename) %}
                <img class="article-detail-image align-self-start mr-3 rounded" src="{{ asset(article.imagePath) }}">
            {% endif %}

            <div class="media-body d-inline-block align-self-center">
                <h1 class="mb-2">{{ article.title }}</h1>
                <div class="d-flex mb-2">
                    {% if article.author %}
                    <div class="text-muted align-self-center">
                        <img class="article-author-img rounded-circle mr-2" src="{{ article.avatarPath }}">
                        {{ article.author }}
                    </div>
                    {% endif %}

                    <div class="text-muted align-self-center ml-4"><i class="fas fa-clock size-is-"></i>
                        {{ article.publishedAt ? article.publishedAt|ago : 'Не опубликована' }}
                    </div>
                </div>
                {% if article.tags|length %}
                    <div class="mb-2 d-flex">
                        {% include 'partial/article_tags.html.twig' with { tags: article.tags } %}
                    </div>
                {% endif %}

                <div class="mb-2">
                    <div class="align-self-center article-detail-arrows" data-id="voteBlock">
                        <span class="{{ article.voteCount < 0 ? 'text-danger' : 'text-success' }}" data-id="voteCount">
                            {{ article.voteCount ? article.voteCount : 'Нет голосов' }}
                        </span>
                        <button class="btn btn-success ml-3"
                            data-id="voteButton"
                            data-href="{{ path('app_articles_vote_up', {slug: article.slug}) }}">
                            <i class="fas fa-arrow-up"></i>
                        </button>
                        <button class="btn btn-danger"
                            data-id="voteButton"
                            data-href="{{ path('app_articles_vote_down', {slug: article.slug}) }}">
                            <i class="fas fa-arrow-down"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-12 mt-2 mb-4">
        {{ article.body|cached_markdown }}
    </div>


    <div class="col-sm-12 mb-4">
        <h3><i class="pr-3 far fa-comment text-secondary"></i>Комментариев {{ article.nonDeletedComments|length }}</h3>
        <hr>

        <div class="row mb-4">
            <div class="col-sm-12">
                <div class="comment-container align-self-start col-sm-6">
                    <div class="form-group">
                        <textarea class="form-control" rows="2"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Комментировать</button>
                </div>
            </div>
        </div>

        {% for comment in article.nonDeletedComments %}
            <div class="row mt-4">
                <div class="col-sm-12">
                    <div class="media">
                        <img class="align-self-start comment-img rounded-circle" src="{{ asset('images/profile.png') }}">
                        <div class="media-body align-self-start col-sm-6">
                            <b>{{ comment.authorName }}</b>
                            <small>{{ comment.createdAt|ago }}</small>
                            <br>
                            <span class="comment">{{ comment.content|cached_markdown }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock %}